### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Lebofly** [DomiStyle/docker-eldewrito#1] opened 2018-04-24 01:58 UTC
Hey there,

Fresh install and using docker-composer up. 

```
root@voxelservers:/home/daemon-data/docker-eldewrito# docker-compose up
/bin/sh: /tmp/_MEI7v3Eiz/libtinfo.so.5: no version information available (required by /bin/sh)
Starting docker-eldewrito_eldewrito_1 ... done
Attaching to docker-eldewrito_eldewrito_1
eldewrito_1  | Initializing
eldewrito_1  | Starting virtual frame buffer
eldewrito_1  | Starting dedicated server
eldewrito_1  | 0012:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
eldewrito_1  | 0012:fixme:process:SetProcessDEPPolicy (1): stub
eldewrito_1  | 0012:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
eldewrito_1  | 001c:fixme:process:SetProcessShutdownParameters (00000380, 00000000): partial stub.
eldewrito_1  | 001f:err:module:import_dll Library MSVCR100_CLR0400.dll (which is needed by L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorsvw.exe") not found
eldewrito_1  | 001f:err:module:import_dll Library mscoree.dll (which is needed by L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorsvw.exe") not found
eldewrito_1  | 001f:err:module:attach_dlls Importing dlls for L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorsvw.exe" failed, status c0000135
eldewrito_1  | 000f:err:service:process_send_command service protocol error - failed to write pipe!
eldewrito_1  | 000f:fixme:service:scmdatabase_autostart_services Auto-start service L"clr_optimization_v4.0.30319_64" failed to start: 1053
eldewrito_1  | 0009:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
eldewrito_1  | 0038:fixme:ver:GetCurrentPackageId (0xbaafe8c (nil)): stub
eldewrito_1  | 0009:fixme:d3d:wined3d_guess_card No card selector available for card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 5.0, 256 bits)").
eldewrito_1  | 0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
eldewrito_1  | 0009:fixme:win:EnumDisplayDevicesW ((null),0,0x32f8e4,0x00000000), stub!
eldewrito_1  | 0009:fixme:ole:CoInitializeSecurity ((nil),-1,(nil),(nil),0,3,(nil),0,(nil)) - stub!
eldewrito_1  | 0009:fixme:wbemprox:client_security_SetBlanket 0xb8cd182c, 0x190a18, 10, 0, (null), 3, 3, (nil), 0x00000000
eldewrito_1  | 0009:fixme:wbemprox:client_security_Release 0xb8cd182c
eldewrito_1  | 0009:fixme:wbemprox:enum_class_object_Next timeout not supported
eldewrito_1  | 0009:err:wgl:X11DRV_wglCreateContextAttribsARB Context creation failed (error 1)
eldewrito_1  | 0009:err:wgl:X11DRV_wglCreateContextAttribsARB Context creation failed (error 1)
eldewrito_1  | 0009:fixme:d3d:wined3d_guess_card No card selector available for card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 5.0, 256 bits)").
eldewrito_1  | 0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
eldewrito_1  | 0009:fixme:win:EnumDisplayDevicesW ((null),0,0x32f5a4,0x00000000), stub!
eldewrito_1  | 0009:fixme:d3d:wined3d_guess_card No card selector available for card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 5.0, 256 bits)").
eldewrito_1  | 0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
eldewrito_1  | 0009:fixme:win:EnumDisplayDevicesW ((null),0,0x32f954,0x00000000), stub!
eldewrito_1  | 0009:fixme:d3d:swapchain_init The application requested more than one back buffer, this is not properly supported.
eldewrito_1  | Please configure the application to use double buffering (1 back buffer) if possible.
eldewrito_1  | 0009:fixme:win:RegisterRawInputDevices Unhandled flags 0x230 for device 0.
eldewrito_1  | ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
eldewrito_1  | ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
eldewrito_1  | ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
eldewrito_1  | ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
eldewrito_1  | ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
eldewrito_1  | ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
eldewrito_1  | ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
eldewrito_1  | ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
eldewrito_1  | ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
eldewrito_1  | ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
eldewrito_1  | ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
eldewrito_1  | ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
eldewrito_1  | ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
eldewrito_1  | ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
eldewrito_1  | ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
eldewrito_1  | ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
eldewrito_1  | 0041:fixme:ras:RasEnumConnectionsW (0x13b85d10,0xfdff8bc,0xfea0004),stub!
eldewrito_1  | 0041:fixme:ras:RasEnumConnectionsW RAS support is not implemented! Configure program to use LAN connection/winsock instead!

```

**Comment by wallopthecat** [comment] 2018-04-24 02:51
I get the same leading errors. Game and config and log folders all exist and bound

```
Attaching to dockereldewrito_eldewrito_1
eldewrito_1  | Initializing
eldewrito_1  | Starting virtual frame buffer
eldewrito_1  | Starting dedicated server
eldewrito_1  | 0012:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
eldewrito_1  | 0012:fixme:process:SetProcessDEPPolicy (1): stub
eldewrito_1  | 0012:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
eldewrito_1  | 001c:fixme:process:SetProcessShutdownParameters (00000380, 00000000): partial stub.
eldewrito_1  | 001f:err:module:import_dll Library MSVCR100_CLR0400.dll (which is needed by L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorsvw.exe") not found
eldewrito_1  | 001f:err:module:import_dll Library mscoree.dll (which is needed by L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorsvw.exe") not found
eldewrito_1  | 001f:err:module:attach_dlls Importing dlls for L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorsvw.exe" failed, status c0000135
eldewrito_1  | 000f:err:service:process_send_command service protocol error - failed to write pipe!
eldewrito_1  | 000f:fixme:service:scmdatabase_autostart_services Auto-start service L"clr_optimization_v4.0.30319_64" failed to start: 1053
eldewrito_1  | 0009:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
```

**Comment by DomiStyle** [comment] 2018-04-24 06:47
A new image is building on Docker Hub right now. It should reduce image size and solve those issues. Master server announcement is also working now and CPU spikes are gone.

0.6-test1 is going to be built with Wine stable
0.6-test2 is going to be built with Wine staging

I would recommend test2 for now since it was tested.

**Comment by Lebofly** [comment] 2018-04-24 06:52
- SNIP -

Guessing I have to wait for the push before it'll work, my bad

**Comment by DomiStyle** [comment] 2018-04-24 06:56
@Lebofly Did you build it yourself? It's not on the Docker Hub yet.

**Comment by Lebofly** [comment] 2018-04-24 07:04
I haven't used Docker much, how would I go about building myself for future reference?

**Comment by DomiStyle** [comment] 2018-04-24 07:09
Pull the git repository, change into the directory and execute

    docker build -t lebofly/eldewrito .

Docker will take care of the rest.

**Comment by DomiStyle** [comment] 2018-04-24 07:49
@Lebofly You can try 0.6-test3 now. You will have to recreate the container before every start until test4 is done.

edit: test4 is up, using Wine stable
edit2: test5 is up, using Wine staging

**Comment by DomiStyle** [comment] 2018-04-24 07:52
A correct startup with test3 should look like this:


    4/24/2018 9:51:00 AMInitializing
    4/24/2018 9:51:00 AMStarting virtual frame buffer
    4/24/2018 9:51:00 AMStarting dedicated server
    4/24/2018 9:51:00 AM000b:fixme:winediag:start_process Wine Staging 3.6 is a testing version containing experimental patches.
    4/24/2018 9:51:00 AM000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
    4/24/2018 9:51:02 AM0009:fixme:kerberos:kerberos_SpInstanceInit 65536,0x7da3c3a0,(nil): stub
    4/24/2018 9:51:02 AM0009:fixme:nvapi:unimplemented_stub function 0x694d52e is unimplemented!
    4/24/2018 9:51:02 AM0009:fixme:nvapi:unimplemented_stub function 0x694d52e is unimplemented!
    4/24/2018 9:51:10 AM002f:fixme:ver:GetCurrentPackageId (0xbabfe9c (nil)): stub
    4/24/2018 9:51:10 AM0009:fixme:d3d:wined3d_guess_card No card selector available for card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 5.0, 128 bits)").
    4/24/2018 9:51:10 AM0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
    4/24/2018 9:51:10 AM0009:fixme:ole:CoInitializeSecurity ((nil),-1,(nil),(nil),0,3,(nil),0,(nil)) - stub!
    4/24/2018 9:51:10 AM0009:fixme:wbemprox:client_security_SetBlanket 0xb862282c, 0x1922e8, 10, 0, (null), 3, 3, (nil), 0x00000000
    4/24/2018 9:51:10 AM0009:fixme:wbemprox:client_security_Release 0xb862282c
    4/24/2018 9:51:10 AM0009:fixme:wbemprox:enum_class_object_Next timeout not supported
    4/24/2018 9:51:10 AM0009:fixme:d3d:wined3d_guess_card No card selector available for card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 5.0, 128 bits)").
    4/24/2018 9:51:11 AM0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
    4/24/2018 9:51:11 AM0009:fixme:d3d:wined3d_guess_card No card selector available for card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 5.0, 128 bits)").
    4/24/2018 9:51:11 AM0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
    4/24/2018 9:51:11 AM0009:fixme:d3d:swapchain_init The application requested more than one back buffer, this is not properly supported.
    4/24/2018 9:51:11 AMPlease configure the application to use double buffering (1 back buffer) if possible.
    4/24/2018 9:51:11 AM0009:fixme:win:RegisterRawInputDevices Unhandled flags 0x230 for device 0.
    4/24/2018 9:51:12 AMALSA lib confmisc.c:768:(parse_card) cannot find card '0'
    4/24/2018 9:51:12 AMALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
    4/24/2018 9:51:12 AMALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
    4/24/2018 9:51:12 AMALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
    4/24/2018 9:51:12 AMALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
    4/24/2018 9:51:12 AMALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
    4/24/2018 9:51:12 AMALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
    4/24/2018 9:51:12 AMALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
    4/24/2018 9:51:12 AMALSA lib confmisc.c:768:(parse_card) cannot find card '0'
    4/24/2018 9:51:12 AMALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
    4/24/2018 9:51:12 AMALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
    4/24/2018 9:51:12 AMALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
    4/24/2018 9:51:12 AMALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
    4/24/2018 9:51:12 AMALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
    4/24/2018 9:51:12 AMALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
    4/24/2018 9:51:12 AMALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default

**Comment by Lebofly** [comment] 2018-04-24 11:57
Will try now and update this post

```

root@voxelservers:/home/daemon-data/docker-eldewrito/git# docker-compose up
/bin/sh: /tmp/_MEIWhFyQo/libtinfo.so.5: no version information available (requir                                            ed by /bin/sh)
Creating network "git_default" with the default driver
Creating git_eldewrito_1 ... done
Attaching to git_eldewrito_1
eldewrito_1  | Initializing
eldewrito_1  | Starting virtual frame buffer
eldewrito_1  | Starting dedicated server
eldewrito_1  | 0012:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
eldewrito_1  | 0012:fixme:process:SetProcessDEPPolicy (1): stub
eldewrito_1  | 0012:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
eldewrito_1  | 0019:fixme:process:SetProcessShutdownParameters (00000380, 000000                                            00): partial stub.
eldewrito_1  | 001c:err:module:import_dll Library MSVCR100_CLR0400.dll (which is                                             needed by L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorsvw.exe")                                             not found
eldewrito_1  | 001c:err:module:import_dll Library mscoree.dll (which is needed b                                            y L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorsvw.exe") not foun                                            d
eldewrito_1  | 001c:err:module:attach_dlls Importing dlls for L"C:\\windows\\Mic                                            rosoft.NET\\Framework64\\v4.0.30319\\mscorsvw.exe" failed, status c0000135
eldewrito_1  | 000f:err:service:process_send_command service protocol error - fa                                            iled to write pipe!
eldewrito_1  | 000f:fixme:service:scmdatabase_autostart_services Auto-start serv                                            ice L"clr_optimization_v4.0.30319_64" failed to start: 1053
eldewrito_1  | 0009:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or i                                            s outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can                                             find it in the winbind package of your distribution.
eldewrito_1  | 0039:fixme:ver:GetCurrentPackageId (0xbaafe8c (nil)): stub
eldewrito_1  | 0009:fixme:d3d:wined3d_guess_card No card selector available for                                             card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 5.0, 256 bits)").
eldewrito_1  | 0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset                                             scale factor detection failed, using fallback value 2^23.
eldewrito_1  | 0009:fixme:win:EnumDisplayDevicesW ((null),0,0x32f8e4,0x00000000)                                            , stub!
eldewrito_1  | 0009:fixme:ole:CoInitializeSecurity ((nil),-1,(nil),(nil),0,3,(ni                                            l),0,(nil)) - stub!
eldewrito_1  | 0009:fixme:wbemprox:client_security_SetBlanket 0xb8ce482c, 0x18fc                                            20, 10, 0, (null), 3, 3, (nil), 0x00000000
eldewrito_1  | 0009:fixme:wbemprox:client_security_Release 0xb8ce482c
eldewrito_1  | 0009:fixme:wbemprox:enum_class_object_Next timeout not supported
eldewrito_1  | 0009:err:wgl:X11DRV_wglCreateContextAttribsARB Context creation f                                            ailed (error 1)
eldewrito_1  | 0009:err:wgl:X11DRV_wglCreateContextAttribsARB Context creation f                                            ailed (error 1)
eldewrito_1  | 0009:fixme:d3d:wined3d_guess_card No card selector available for                                             card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 5.0, 256 bits)").
eldewrito_1  | 0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset                                             scale factor detection failed, using fallback value 2^23.
eldewrito_1  | 0009:fixme:win:EnumDisplayDevicesW ((null),0,0x32f5a4,0x00000000)                                            , stub!
eldewrito_1  | 0009:fixme:d3d:wined3d_guess_card No card selector available for                                             card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 5.0, 256 bits)").
eldewrito_1  | 0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset                                             scale factor detection failed, using fallback value 2^23.
eldewrito_1  | 0009:fixme:win:EnumDisplayDevicesW ((null),0,0x32f954,0x00000000)                                            , stub!
eldewrito_1  | 0009:fixme:d3d:swapchain_init The application requested more than                                             one back buffer, this is not properly supported.
eldewrito_1  | Please configure the application to use double buffering (1 back                                             buffer) if possible.
eldewrito_1  | 0009:fixme:win:RegisterRawInputDevices Unhandled flags 0x230 for                                             device 0.
eldewrito_1  | ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
eldewrito_1  | ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_car                                            d_driver returned error: No such file or directory
eldewrito_1  | ALSA lib confmisc.c:392:(snd_func_concat) error evaluating string                                            s
eldewrito_1  | ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_con                                            cat returned error: No such file or directory
eldewrito_1  | ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
eldewrito_1  | ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_ref                                            er returned error: No such file or directory
eldewrito_1  | ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such                                             file or directory
eldewrito_1  | ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
eldewrito_1  | ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
eldewrito_1  | ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_car                                            d_driver returned error: No such file or directory
eldewrito_1  | ALSA lib confmisc.c:392:(snd_func_concat) error evaluating string                                            s
eldewrito_1  | ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_con                                            cat returned error: No such file or directory
eldewrito_1  | ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
eldewrito_1  | ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_ref                                            er returned error: No such file or directory
eldewrito_1  | ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such                                             file or directory
eldewrito_1  | ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
eldewrito_1  | 0042:fixme:ras:RasEnumConnectionsW (0x13b83e48,0xfdff8bc,0xfea0004),stub!
eldewrito_1  | 0042:fixme:ras:RasEnumConnectionsW RAS support is not implemented! Configure program to use LAN connection/winsock instead!

```

**Comment by DomiStyle** [comment] 2018-04-24 12:09
Did you change the image to domistyle/eldewrito:0.6-test5?

**Comment by Lebofly** [comment] 2018-04-24 13:16
Now I did, looks like it's working

```

Status: Downloaded newer image for domistyle/eldewrito:0.6-test5
Recreating git_eldewrito_1 ... done
Attaching to git_eldewrito_1
eldewrito_1  | Initializing
eldewrito_1  | Cleaning up
eldewrito_1  | Starting virtual frame buffer
eldewrito_1  | Starting dedicated server
eldewrito_1  | 000b:fixme:winediag:start_process Wine Staging 3.6 is a testing v                                             ersion containing experimental patches.
eldewrito_1  | 000b:fixme:winediag:start_process Please mention your exact versi                                             on when filing bug reports on winehq.org.
eldewrito_1  | 0009:fixme:kerberos:kerberos_SpInstanceInit 65536,0x7da333a0,(nil                                             ): stub
eldewrito_1  | 0009:fixme:nvapi:unimplemented_stub function 0x694d52e is unimple                                             mented!
eldewrito_1  | 0009:fixme:nvapi:unimplemented_stub function 0x694d52e is unimple                                             mented!
eldewrito_1  | 002f:fixme:ver:GetCurrentPackageId (0xbabfe9c (nil)): stub
eldewrito_1  | 0009:fixme:d3d:wined3d_guess_card No card selector available for                                              card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 5.0, 256 bits)").
eldewrito_1  | 0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset                                              scale factor detection failed, using fallback value 2^23.
eldewrito_1  | 0009:fixme:ole:CoInitializeSecurity ((nil),-1,(nil),(nil),0,3,(ni                                             l),0,(nil)) - stub!
eldewrito_1  | 0009:fixme:wbemprox:client_security_SetBlanket 0xb8da082c, 0x192d                                             c0, 10, 0, (null), 3, 3, (nil), 0x00000000
eldewrito_1  | 0009:fixme:wbemprox:client_security_Release 0xb8da082c
eldewrito_1  | 0009:fixme:wbemprox:enum_class_object_Next timeout not supported
eldewrito_1  | 0009:fixme:d3d:wined3d_guess_card No card selector available for                                              card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 5.0, 256 bits)").
eldewrito_1  | 0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset                                              scale factor detection failed, using fallback value 2^23.
eldewrito_1  | 0009:fixme:d3d:wined3d_guess_card No card selector available for                                              card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 5.0, 256 bits)").
eldewrito_1  | 0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset                                              scale factor detection failed, using fallback value 2^23.
eldewrito_1  | 0009:fixme:d3d:swapchain_init The application requested more than                                              one back buffer, this is not properly supported.
eldewrito_1  | Please configure the application to use double buffering (1 back                                              buffer) if possible.
eldewrito_1  | 0009:fixme:win:RegisterRawInputDevices Unhandled flags 0x230 for                                              device 0.
eldewrito_1  | ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
eldewrito_1  | ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_car                                             d_driver returned error: No such file or directory
eldewrito_1  | ALSA lib confmisc.c:392:(snd_func_concat) error evaluating string                                             s
eldewrito_1  | ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_con                                             cat returned error: No such file or directory
eldewrito_1  | ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
eldewrito_1  | ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_ref                                             er returned error: No such file or directory
eldewrito_1  | ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such                                              file or directory
eldewrito_1  | ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
eldewrito_1  | ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
eldewrito_1  | ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_car                                             d_driver returned error: No such file or directory
eldewrito_1  | ALSA lib confmisc.c:392:(snd_func_concat) error evaluating string                                             s
eldewrito_1  | ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_con                                             cat returned error: No such file or directory
eldewrito_1  | ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
eldewrito_1  | ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_ref                                             er returned error: No such file or directory
eldewrito_1  | ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such                                              file or directory
eldewrito_1  | ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default

```

**Comment by DomiStyle** [comment] 2018-04-24 13:24
Check if you can reach it with http://server_ip:11775 and you're done here.

**Comment by wallopthecat** [comment] 2018-04-24 14:08
My instance now just hangs here:
```
Status: Downloaded newer image for domistyle/eldewrito:0.6-test5
Recreating dockereldewrito_eldewrito_1 ...
Recreating dockereldewrito_eldewrito_1 ... done
Attaching to dockereldewrito_eldewrito_1
eldewrito_1  | Initializing
eldewrito_1  | Cleaning up
eldewrito_1  | Starting virtual frame buffer
eldewrito_1  | Starting dedicated server
eldewrito_1  | 000b:fixme:winediag:start_process Wine Staging 3.6 is a testing version containing experimental patches.
eldewrito_1  | 000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
eldewrito_1  | 0009:fixme:kerberos:kerberos_SpInstanceInit 65536,0x7da2a3a0,(nil): stub
```

Netstat shows ports opened but http doesn't load. Ignore ipv6, it is a known docker issue and they are apparently listening on ipv4 too
```
➜  ~ sudo netstat -tulnp |grep 177
tcp6       0      0 :::11775                :::*                    LISTEN      4754/docker-proxy
tcp6       0      0 :::11776                :::*                    LISTEN      4742/docker-proxy
tcp6       0      0 :::11777                :::*                    LISTEN      4711/docker-proxy
udp6       0      0 :::11774                :::*                                4766/docker-proxy
```

**Comment by DomiStyle** [comment] 2018-04-24 14:10
@wallopthecat Interesting, somebody on Discord has the same issue.

Can you try running the container with --privileged and --net=host for testing purposes?

**Comment by wallopthecat** [comment] 2018-04-24 14:17
Sure thing, What is the discord you are in? Or should I keep the results in this ticket? Also any idea how to run privileged in docker compose?

**Comment by DomiStyle** [comment] 2018-04-24 14:19
@wallopthecat  I'm in the official ElDewrito Discord in the #hosting-help channel.

https://goo.gl/01GtMK#discord

**Comment by disconsented** [comment] 2018-04-25 01:38
I can confirm this as well
```yml
version: '2'

services:
  eldewrito:
    image: domistyle/eldewrito:0.6-test5
    network_mode: "host"
    restart: always
    ports:
      - 11774:11774/udp
      - 11775:11775/tcp
      - 11776:11776/tcp
      - 11777:11777/tcp
    volumes:
      - /home/disconsented/eld/halo:/game
      - /home/disconsented/eld/halo/config:/config
      - /home/disconsented/eld/halo/logs:/logs
    cap_add:
      - SYS_PTRACE
    privileged: true
```
results in

```bash
[disconsented@nikola-server ~]$ docker-compose logs
Attaching to disconsented_eldewrito_1
eldewrito_1  | Initializing
eldewrito_1  | Cleaning up
eldewrito_1  | Starting virtual frame buffer
eldewrito_1  | Starting dedicated server
eldewrito_1  | 000b:fixme:winediag:start_process Wine Staging 3.6 is a testing version containing experimental patches.
eldewrito_1  | 000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
eldewrito_1  | 0009:fixme:kerberos:kerberos_SpInstanceInit 65536,0x7da5c3a0,(nil): stub
```
In case it matters:
Arch Linux
Docker version 18.04.0-ce, build 3d479c0af6

**Comment by DomiStyle** [comment] 2018-04-25 06:43
@disconsented I'm seeing a lot of Docker 18.04.0-ce when this is failing so I'm going to try if I can reproduce it there.

Just for reference, I can confirm the test5 image is working on the following hosts/engines:
* RancherOS v1.3.0 (4.9.80), 17.09.1-ce
* Debian 8 (4.9.0), 17.03.1-ce

**Comment by disconsented** [comment] 2018-04-25 09:23
Tried Docker version 17.09.0-ce, build afdb6d44a8 and Docker version 17.03.1-ce, build c6d412e329, no change.

**Comment by DomiStyle** [comment] 2018-04-25 10:56
I was able to reproduce this now, looking into it.

**Comment by DomiStyle** [comment] 2018-04-25 11:38
Update: I have found chowning the game directory on the host works.

    chown root:root /path/to/game -R

Can anbody confirm? @disconsented @wallopthecat

**Comment by wallopthecat** [comment] 2018-04-25 17:09
Chowning as root worked, thanks @DomiStyle for the debugging!

**Comment by DomiStyle** [comment] 2018-04-25 17:33
@wallopthecat Good to hear. Gonna close this issue now.

Create a new one if anybody still has this issue.

**Closed as completed by DomiStyle** 2018-04-25 17:33 UTC

**Comment by disconsented** [comment] 2018-04-25 20:51
Yep that was the problem, thanks!
